### ISSUE TITLE
The addon doesn't work in Blender 3

### ISSUE THREAD

**Issue by microcoder** [Ocupe/Projectors#10]
Hi!

The addon doesn't work in Blender 3. The problem is related to the fix of the spotlight in Blender 3. This is a bug: [Spot light no longer projecting an image texture in Blender 3](https://developer.blender.org/T93565)

**Comment by Ocupe** [comment]
Thank you for creating the issue. I'll look into it during the weekend.

**Comment by demmaone** [comment]
Working fine on Blender 3.0.0 now.
