### ISSUE TITLE
Clarity on projector settings

### ISSUE THREAD

**Issue by aarrushi** [Ocupe/Projectors#11]
This is a really useful add-on! I am trying to project different images onto a scene in blender and had a few doubts:

- Is the H x W hardcoded with the aspect ratio? e.g. 1000x1000 with square? What happens if my image being projected is 400x400 - would it be stretched to 1000 before projecting?

- Throw ratio is decided based on the width and distance to the plane where we project. But what happens if we want to project onto a 3D surface with varying depths?

**Comment by aarrushi** [comment]
The projector also has a camera object associated with it. Is there a relation between the focal length of this camera and the throw ratio of the projector? Basically, what would be the accurate way to extract the focal length of the projector?

**Comment by Ocupe** [comment]
On the camera you can change the Lens Unit from "Fild of View" to "Millimeters" then you get the "Focal Length" in the row above that. But be aware the focal lenght is dependent on the sensor size.

<img width="313" alt="Screenshot 2022-03-10 at 23 36 04" src="https://user-images.githubusercontent.com/11357413/157766910-2b0e3059-bf06-4c91-8509-efc093147e96.png">
<img width="305" alt="Screenshot 2022-03-10 at 23 39 31" src="https://user-images.githubusercontent.com/11357413/157766915-18f65424-6b45-4025-88e5-5720a2241f92.png">
