### ISSUE TITLE
Doesn't work in Eevee renderer

### ISSUE THREAD

**Issue by dramaticrobotic** [Ocupe/Projectors#16]
The title explains the issue well enough, but this is actually a common issue that still hasn't been figured out, and the node setups that are currently available don't provide any dynamic lighting.

**Comment by Ocupe** [comment]
@dramaticrobotic sorry for the late reply. Last time I checked, there were no light textures for spotlights in Eevee. Since the plugin is based on it, Eevee is not yet supported. 
If you have new info about light textures in Eevee please let me know.
