### ISSUE TITLE
Ndi source

### ISSUE THREAD

**Issue by k-Gabe** [Ocupe/Projectors#2]
Hi, I have found this tool very useful, especially for simulation.
I do video mapping,and this tool is great because of the ability to project on object’s faces. once finished And rendered my animation , I will like to test it without having a physical object.
Here, your plugin.
The problem is that to play animation I have to use external mapping sw, which can send video over Ethernet using ndi.
But this plugin can play video/photo files only.
Can you add this feature? Keep in mind that ndi should be an open source protocol.
Thanks, Regards KGabe

**Comment by Ocupe** [comment]
Hello @k-Gabe, I am glad to hear that you have useage for the add-on.
I'm afraid I have to say no to your request. I don't see any way how to simply integrate NDI into the add-on.

I'm also afraid that I don't fully understand your intention or your goal. Are you trying to use the add-on in some sort of live setup? If you're willing to elaborate on your setup I'm happy to point out some possible alternative solutions.
