### ISSUE TITLE
Open image with python script

### ISSUE THREAD

**Issue by mnee15** [Ocupe/Projectors#23]
Hello, I want to change projection image in python script.

```
projector = bpy.data.objects['Projector']  
projector.proj_settings.projected_texture = 'custom_texture'  
bpy.ops.projector.image(filepath="image_path")
```

but projection image does not change.

Do you know the solution?

**Comment by Ocupe** [comment]
@mnee15 I am not sure if this will work. 🤔 I never developed the plugin with python scripts in mind. If I can find some time this weekend I will try to find a way.

**Comment by richyjunior** [comment]
@mnee15 
I had same problem with you. I just solved it by reading the ui.py. It may not be the best solution, but it worked for me.
```python
projector = bpy.data.objects['Projector']  
projector.proj_settings.projected_texture = 'custom_texture'  
node = projector.children[0].data.node_tree.nodes['Image Texture']
image_path="D:\\theLocationOfYourImage\\"
image_filename="name.png"
bpy.data.images.load(image_path+image_filename,check_existing=True)
node.image=bpy.data.images[image_filename]

bpy.context.scene.render.filepath =  "//result.png"
bpy.ops.render.render(use_viewport = True,write_still=True)

```
Hope this is useful for someone.

**Comment by Ocupe** [comment]
@richyjunior Thanks for sharing. 👍 
I decided not to spend time working on this, but I'm glad it works with our sample code.
