### ISSUE TITLE
Vertical lens shift result depends on aspect ratio

### ISSUE THREAD

**Issue by drlight-code** [Ocupe/Projectors#25]
Hi @Ocupe, can you explain the definition of lens shift used in your implementation? To make the projector vertically aligned with the bottom of the image, I have to enter 28.125% which I determined empirically. Please see the attached screenshot.
![lens-shift](https://github.com/Ocupe/Projectors/assets/6815246/bc49fa31-1c70-47fc-baad-bcdae58271e0)

It would be great to add a description or a link to some document in the Wiki or README so that it's easier to see how the numbers should be interpreted. I found several different definitions of the lens shift in percent, but neither matches what I currently observe within Blender.
https://helpguide.sony.net/vpl/xw5000/v1/en/contents/TP1000558303.html
https://norxe.com/wp-content/uploads/product-support-norxe-lens-shift-explained.pdf

Or maybe this is also a problem related to Blender version 3.6? I saw that there is already a case distinction for different versions when the camera settings are adjusted based on the lens shift.
https://github.com/Ocupe/Projectors/blob/master/projector.py#L307C21-L312

Thank you!

**Comment by drlight-code** [comment]
I did some testing and found that the lens shift is dependent on the format that I choose for the projector. For a lens shift of -50/0/50 I get the following results for 1080p and Square. It seems that for Square the shift calculation is correct. Maybe for the other formats the aspect ratio needs to be taken into account?
![lens-shift-1080p](https://github.com/Ocupe/Projectors/assets/6815246/dfc8f20d-01a3-4bf5-ad2f-80a360e623b2)
![lens-shift-square](https://github.com/Ocupe/Projectors/assets/6815246/b0bee53c-6e39-433f-8bec-22c2d49ef7dd)

**Comment by drlight-code** [comment]
I opened a pull request #26 that fixes the problem for me by dividing with the vertical aspect ratio. Since the throw ratio relates distance and width, the additional factor is required. I multiply with the inverse for numerical / performance reasons, probably not really important.
![lens-shift-fixed](https://github.com/Ocupe/Projectors/assets/6815246/60d931d3-2dd6-4717-b62a-24b2474acb7f)

**Comment by Ocupe** [comment]
@drlight-code thanks for looking into this 👍. 
I will need some more time to update my test setup and check everything, but this is great work and should be the default behavior. 🙏

**Comment by Ocupe** [comment]
fixed with #26 🎊
