### ISSUE TITLE
Interdependent parameter settings are not updated correctly

### ISSUE THREAD

**Issue by drlight-code** [Ocupe/Projectors#27]
If I change a projector's throw ratio, the shift offsets are not recalculated, although their calculation depends on the throw ratio.

In the test scene I have three projectors with a throw ratio of 1 and a lens shift of 50% (after applying #26).
![param-update-pre](https://github.com/Ocupe/Projectors/assets/6815246/10847054-e7f7-4c61-9a7e-1f0e7c54ec5c)

If I now change the throw ratio to 0.8, I get the following result.
![param-update-post](https://github.com/Ocupe/Projectors/assets/6815246/27f88c6b-a62c-462b-aff1-57bbeb0513a6)

If I then just type in the same numbers again for the vertical shift (which will trigger `update_lens_shift`) I see the expected result.
![param-update-post2](https://github.com/Ocupe/Projectors/assets/6815246/92df6f61-ddde-47e7-b06f-91fcd33bca2a)

**Comment by Ocupe** [comment]
Should be fixed by #30.
Thank you for reporting 👍
