### ISSUE TITLE
Blender 3.6.2 Instal Fail

### ISSUE THREAD

**Issue by PLAN8VR** [Ocupe/Projectors#33]
Hi, I just tried to install on Blender V 3.6.2 - module will load, but upon activation I get the error ...

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Projectors-0'

**Comment by Ocupe** [comment]
@solosails thank you for reporting! 👍 
I seem to have forgotten how to do a proper release. 🤦 
New release with a properly packaged add-on here: https://github.com/Ocupe/Projectors/releases

**Comment by solosails** [comment]
Awesome - thank you!

That installed and activated correctly - thanks!
