### ISSUE TITLE
Feature Request: Projection mapping and projection texture baking

### ISSUE THREAD

**Issue by jurassicjordan** [Ocupe/Projectors#34]
This might be a difficult to explain and complicated addition to make, but would make blender and your addon very powerful in competition with software like Mapping Matters. Essentially, what it is is being able to input one image like an unwrapped UV map (or perhaps the same image input into all projector objects) and have one or more projectors project the texture onto the object. of course the inverse would be amazing too, to be able to take an object with an image texture, select the projectors you want to create a mapping for, and click a bake button which will bake the object textures into projector images that the beamers project, and set the object's material to a matte white. 

I don't expect this to be added but its something to consider

**Comment by Ocupe** [comment]
Hey @jurassicjordan, thanks for your message. That sounds like a cool project, but I'm afraid it's out of scope for this add-on :)
