### ISSUE TITLE
Python Scripts errors on Blender 4.0

### ISSUE THREAD

**Issue by Anemovatis** [Ocupe/Projectors#35]
I know it's too soon but there it is :)

**Comment by Ocupe** [comment]
Thanks @Anemovatis 😄 
I'll try to take a look at the weekend.

**Comment by ffurrer** [comment]
Is there any update on this?

It seems that the node group structure changed, see [here](https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API#Node_Groups). I managed to get rid of the errors but it doesn't seem to work yet.

In `add_projector_node_tree_to_spot(spot)` I tried to change
```python
output = node_group.outputs
output.new('NodeSocketVector', 'texture vector')
output.new('NodeSocketColor', 'color')
```
to
```python
node_group.interface.new_socket(name="texture vector", in_out='OUTPUT', socket_type='NodeSocketVector')
node_group.interface.new_socket(name="color", in_out='OUTPUT', socket_type='NodeSocketColor')
```
similarly also in `create_pixel_grid_node_group()`.

Like this, I got rid of the errors but the projection didn't seem to work, I also have no comparison of how it should behave, tried this plugin for the first time ;).

Cheers

**Comment by jurassicjordan** [comment]
whats the current state of this? will this be fixed soon?

**Comment by arcadeperfect** [comment]
+1

**Comment by Ocupe** [comment]
Hi, please try the new pre-release and let me know if it solves your problems: https://github.com/Ocupe/Projectors/releases/tag/v2024.0.0-rc1

**Comment by backhausmartin** [comment]
Hello, adding a 2nd projector I have the issue, that after moving/rotation that 2nd projector, some of the projection onto walls shown with Cycles (Viewport Shading) is cut off.
If I disable the new 2nd Spotlight (the light parented below the Projector) the 2nd projector is switched off, and the old 1st projector show the correct image.

**Comment by Ocupe** [comment]
@backhausmartin Could you try it with the new release? If the problem persists, could you provide me with a .blend file, some screenshots or a video? Just to verify that we are talking about the same thing.

**Comment by Ocupe** [comment]
I'm going to close this, but feel free to re-open it if the problem still exists.

**Comment by jurassicjordan** [comment]
am I the only one still having these issues?

**Comment by RobeSantoro** [comment]
I'll check soon and report

**Comment by Ocupe** [comment]
> am I the only one still having these issues?

@jurassicjordan Have you updated to the latest version? The new version does not migrate "old" projectors to work with the new Blender versions. So you have to start over and create new projectors with the new version of the add-on.
