### ISSUE TITLE
Incorrect rendering with 2 or more projectors

### ISSUE THREAD

**Issue by raganmd** [Ocupe/Projectors#38]
This is pretty silly, but there's an edge case where when there are 2 or more projectors present there's some possible occlusion generated. 

![image](https://github.com/Ocupe/Projectors/assets/11582808/393c51bd-15a4-4bf6-b20f-57ad4fb71860)

The issue can be resolve by changing beam shape to 179 degrees instead of 180:

![image](https://github.com/Ocupe/Projectors/assets/11582808/6f287dc1-04a4-49a7-9161-c7c3e818106c)

After changing the spot size:

![image](https://github.com/Ocupe/Projectors/assets/11582808/32ee4350-2b7d-467d-adfa-150151484b3a)

Not a major issue, but thought you might want a heads up on this one.

**Comment by Ocupe** [comment]
Oh wow that's unexpected. I will fix it. Thanks for raising the issue.

**Comment by raganmd** [comment]
Thanks for the fast reply! Also huge thanks for creating this plugin
