### ISSUE TITLE
throw ratio and offset

### ISSUE THREAD

**Issue by mike-iv** [Ocupe/Projectors#4]
Hi Jonas! 
I was pleased with your Projector Add-on for Blender :) And I have a suggestion for changes that, in my opinion, are necessary for this add-on 1) throw ratio, for some ultra-short-focus beamers it parameter starts from 0.18. 2) Some beamers have offset , 
(Figure 1)![540c0e1a5b9e82a15a247a4964c2edddd5fe33df0a8325430dea31c9c67e48f5 (1)](https://user-images.githubusercontent.com/16124856/98926697-b1447b80-24e8-11eb-88d2-e6f5f2db70b6.jpg), this addon has a similar vertical shift parameter, but it is not enough. It will be very cool if it can be done. 3) is it possible to adapt this add-on for luxcorerender, because there you can adjust the reflection of the projection from the mirrors.

**Comment by Ocupe** [comment]
Hey @mike-iv, nice to hear that you find this add-on helpful. 
To answer you questions:
1) The limit for the throw ratio is only a soft limit. If you click into the input field you can enter any number you like.

2) The offset is also a soft limit, you can add what you like. As I researched how manufacturers define the offset for their projectors I found out that there is no standard way and I just picked one, but I forgot which one it was :D. If your interested it's in the [code](https://github.com/Ocupe/Projectors/blob/master/projector.py#L289).

3) Unfortunately I don't know anything about luxcorerender. The add-on relies on light textures so if you can get them to work with lux you could maybe get the functionality to work. Sadly I don't have the time to work on this.

Good Luck

**Comment by mike-iv** [comment]
Okay, thanks for the answer!
