### ISSUE TITLE
Multi projectors, wired mutual effect!

### ISSUE THREAD

**Issue by mrtuttle** [Ocupe/Projectors#40]
When there are multiple projectors on stage, the rotation of one affects the other projections, casting strange shadows.

![Multi_Projectors__Blender 4 0](https://github.com/Ocupe/Projectors/assets/163915671/8c716546-ea59-4918-93bf-6e3ad7d6e04f)
[Multi-Projectors.zip](https://github.com/Ocupe/Projectors/files/14772397/Multi-Projectors.zip)

The problem happens systematically, there are some relative rotations and relative positions between projectors that are more problematic than others, however even in the simple attached scene the strange shadows make the addon difficult to use in situations with multiple projectors. Hope it can be fixed. 

Thank's for your great job!
Really nice addon!

**Comment by Ocupe** [comment]
Hi, have you tried the latest version? Without checking it looks like this bug: https://github.com/Ocupe/Projectors/issues/38

**Comment by mrtuttle** [comment]
Yes! It was the same bug due the Spot Size.
If I reduce it a little then everything works.
I apologize, I hadn't seen the previous solved issues.
Thx!

**Comment by Ocupe** [comment]
@archibald-tuttle, no worries.! I'm glad I have people like you to report issues in such a nice way! 🙂
