### ISSUE TITLE
User testing :) Made it work like this.  

### ISSUE THREAD

**Issue by szat** [Ocupe/Projectors#6]
Hello, as we were saying, I am not sure if I am doing this wrong. 
My Blender version is 2.91.0. 

I do the following steps to get a result. But I cannot follow your tutorial in the previous git Issues. 

Create projector object:

![step1](https://user-images.githubusercontent.com/5555551/101958460-5c704f80-3bd1-11eb-9bd6-10574cb00581.png)

Orient projector manually:

![step2](https://user-images.githubusercontent.com/5555551/101958499-73af3d00-3bd1-11eb-9a88-dc71280277e7.png)

Go into Shading, upload an image:

![step3](https://user-images.githubusercontent.com/5555551/101958532-8590e000-3bd1-11eb-8648-38b149af1458.png)

Maybe I am doing something wrong:

![step4](https://user-images.githubusercontent.com/5555551/101958557-90e40b80-3bd1-11eb-9943-12e078836fde.png)

This seems to fix:

![step5](https://user-images.githubusercontent.com/5555551/101958569-97728300-3bd1-11eb-880f-62a983a684ea.png)

**Comment by Ocupe** [comment]
Thank you for the expatiation (and the new issue :P )!
The add-on is intended to be uses from the panel in the 3D-Viewport. In the 3D-Viewport you can open the N-Panel (I don't actually know the name of the panel but you can open it by pressing the "n" key). There you have a tab called "Projector" with all the settings. 
The reconnecting of the nodes is done by the add-on, so normally you don't have to go into the shader-editor to make changes.  
![Screenshot 2020-12-11 at 23 10 01](https://user-images.githubusercontent.com/11357413/101960034-c6efb280-3c06-11eb-9a9a-1fdcacf09b8d.png)
