### ISSUE TITLE
Possible bug, throw ratio not updated after image upload

### ISSUE THREAD

**Issue by szat** [Ocupe/Projectors#7]
Hello!

After I upload an image to project in custom_textures, I have to reupdate the throw ratio. I have the feeling that the uploaded image is updating some fields, which then override the fields as defined by the throw ratio. 

Try this: with throw ratio 1, render a scene. Then try to reproject that render onto the scene. For me it is often scaled in the wrong way, the throw ratio is still 1. After I reset the throw ratio to 1, the reprojection is correct. 

Are you able to reproduce this behavior?

**Comment by Ocupe** [comment]
Hey @szat, 
yes this is a known bug, I could not find a way to trigger a update when you load a new textures. If you are aware of a way please let me know. Until then you have to do something to trigger the update manually for example by changing some of the settings or by clicking the "Let Image Define Projector Resolution" checkbox (see pic) twice.
![Screenshot 2021-01-17 at 19 03 48](https://user-images.githubusercontent.com/11357413/104851772-4b64dd80-58f7-11eb-916c-5168074e7518.png)
