### ISSUE TITLE
Selective Object Projection / Exclude Objects & Corner Pinning

### ISSUE THREAD

**Issue by Tedcharlesbrown** [Ocupe/Projectors#9]
Hello! First of all, fantastic add-on. Pretty much exactly what I was looking for.

I am a video programmer for theatre / tv & film. I am experimenting with different ways to preview video content. Your add-on is a great way to double-check the throw of the projector. However, a lot of times the projector covers more than the surface we want to cover. This would normally be solved in the video software we are using, It would be amazing though for better / a different option for visualization if there was a way to do it with your add-on.

A potential way I could see this working is for there to be an include or exclude objects option. So if you are spilling onto a back wall, you could exclude that object, or only include the projector surfaces?

Thank you for your time!

**Comment by Tedcharlesbrown** [comment]
Adding onto this as I am doing more experimenting. The ability to corner pin within the raster of the projection would also be extremely useful.

**Comment by Ocupe** [comment]
Hello @Tedcharlesbrown ,
nice to hear that the add-on is useful for you. Unfortunately, your request is a bit out of the scope of this addon. The projector in my add-on is just a spotlight with a light texture. Sadly "Light Linking" or excluding some objects to receive light from a specific light source is currently not supported in Blender ([LINK](https://devtalk.blender.org/t/exclude-light-from-objects/14156)). So there is sadly not much I can do, sorry :( 

Regarding your second request. Unfortunately, this is also a bit beyond my intended scope for the add-on. But as I indicated, the projector is just a spotlight with a light texture. So if you know your way around the node editor you could put together a keystone functionality there.

I hope this was somewhat helpful to you? Have a nice day :)
